name: kbn_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-175.0.dev

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Inter_18pt-Black.ttf
    - family: Inter
      fonts:
        - asset: assets/font/Inter_18pt-Regular.ttf
